 # 1. Install Docker (The Container Engine)
- name: Install software
  hosts: local
  connection: localhost
  become: yes

  tasks:
    - name: Update apt cache
      ansible_builtin.apt:
        update_cache: yes


    - name: ensure dependencies are installed
      ansible.builtin.package:
        name: 
          - bc
          - curl
          - expect
          - git
          - ca-certificates
        status: present

    - name: Add docker gpg key path
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"  

    - name: Add docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        status: present
        mode: "0644"

    - name: Add docker repository 
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
    
    - name: Update apt cache  after adding docker repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Add docker Engine
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

  #2. install jenkins
    - name: install java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: add jenkins gpg
      apt_key: 
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: latest
        udpate_cache: true

    - name: add jenkins repo
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: latest

    - name: install jenkins
      apt:
        name: jenkins
        state: present

#3  Permissions & Services
    - name: add ubuntu and jenkins to docker group
      user:
        name: "{{ item }}" 
        groups: docker
        append: yes
      loop:
        - ubuntu
        - jenkins 

    - name: ensure things doing right
      systemd: 
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: [docker, jenkins]

